package cy.ac.ucy.cs.anyplace.lib.smas.models

import com.google.gson.annotations.SerializedName
import cy.ac.ucy.cs.anyplace.lib.anyplace.models.UserCoordinates

data class FingerprintSendReq(
  // USER:
  @SerializedName("uid")
  val uid: String,
  @SerializedName("sessionkey")
  val sessionkey: String,

  // LOCATION:
  @SerializedName("buid")
  val buid: String,
  @SerializedName("deck")
  val deck: Int,
  @SerializedName("x")
  val x: Double,
  @SerializedName("y")
  val y: Double,

  // TIME:
  @SerializedName("time")
  val time: String,

  // DETECTIONS:
  @SerializedName("cvDetections")
  val cvDetections: List<CvDetectionREQ>,
  @SerializedName("modelid")
  val modelid: Int
) {
  constructor(user: ChatUser, uc: UserCoordinates, time: String,
              detections: List<CvDetectionREQ>, modelId: Int):
      this(user.uid, user.sessionkey,
        uc.buid, uc.level, uc.lat, uc.lon,
        time,
        detections, modelId)

  constructor(user: ChatUser, fe: FingerprintScanEntry):
      this(user.uid, user.sessionkey,
        fe.buid, fe.deck, fe.x, fe.y,
        fe.time,
        fe.cvDetections, fe.modelid)

}

/**
 * Used for storing in file cache
 * has X,Y,Z location, detections, and model
 */
data class FingerprintScanEntry(
  // LOCATION:
  @SerializedName("buid")
  val buid: String,
  @SerializedName("deck")
  val deck: Int,
  @SerializedName("x")
  val x: Double,
  @SerializedName("y")
  val y: Double,

  // TIME:
  @SerializedName("time")
  val time: String,

  // DETECTIONS:
  @SerializedName("cvDetections")
  val cvDetections: List<CvDetectionREQ>,
  @SerializedName("modelid")
  val modelid: Int
) {
  constructor(uc: UserCoordinates, time: String,
              detections: List<CvDetectionREQ>, modelId: Int):
      this(uc.buid, uc.level, uc.lat, uc.lon,
        time,
        detections, modelId)
}


/** RESPONSE when sending a request */
data class FingerprintSendResp(
  @SerializedName("rows")
  val rows: Int,
  @SerializedName("status")
  val status: String,
  @SerializedName("uid")
  val uid: String,
  @SerializedName("descr") // CHECK:DZ
  val descr: String,
)


/**
 * Cv Detection information that is used for the SMAS
 * send-fingerprint request
 */
data class CvDetectionREQ(
  @SerializedName("oid")
  val oid: Int,
  @SerializedName("width")
  val width: Double,
  @SerializedName("height")
  val height: Double,
) {
  constructor(cvd: CvDetection) :
      this(cvd.oid, cvd.width, cvd.height)
}


/**
 * Serialised Computer Vision Detection
 */
data class CvDetection(
  @SerializedName("oid")
  val oid: Int,

  // CHECK in [NMS] method, that uses a heap to discard duplicate detections,
  // we are considering the Width/Height of just the surviving detection
  // NOTE: duplicates due to YOLO's internal design
  @SerializedName("width")
  val width: Double,
  @SerializedName("height")
  val height: Double,

  /** Optical Character Recognition */
  @SerializedName("ocr")
  val ocr: String? = null,

  /** Name of the detection class */
  @SerializedName("detection")
  val detection: String?,
)


/**
 * Request for CV Localization
 */
data class CvLocalizationReq(
  @SerializedName("uid")
  val uid: String,
  @SerializedName("sessionkey")
  val sessionkey: String,

  @SerializedName("time")
  val time: String,

  @SerializedName("buid")
  val buid: String,
  @SerializedName("modelid")
  val modelid: Int,
  @SerializedName("cvDetections")
  val cvDetections: List<CvDetectionREQ>,

  @SerializedName("algorithm")
  val algorithm: Int,
) {
  constructor(u: ChatUser, time: String,
              buid: String, modelId: Int, cvds: List<CvDetectionREQ>, algorithm: Int):
      this(u.uid, u.sessionkey, time, buid, modelId, cvds, algorithm)
}

/**
 * Response after asking the backend for a user's locations.
 *
 * It is possible that it contains multiple results [rocws]
 */
data class CvLocalizationResp(
  @SerializedName("uid")
  val uid: String,
  @SerializedName("rows")
  val rows: List<CvLocalization>,
  @SerializedName("status")
  val status: String,

  @SerializedName("descr")
  val descr: String?=null,
)


/**
 * A single location generated by the SMAS backend
 */
data class CvLocalization(
  @SerializedName("deck")
  val deck: Int,
  @SerializedName("dissimilarity")
  val dissimilarity: Float,
  @SerializedName("flid")
  val flid: Int,
  @SerializedName("x")
  val x: Double,
  @SerializedName("y")
  val y: Double
)

